### ISSUE TITLE
Tutorial: "BigWarp and Ome-Zarr: a match made in Fiji"

### ISSUE THREAD

**Issue by bogovicj** [InsightSoftwareConsortium/GetYourBrainTogether#63]
### Tutorial description

BigWarp is a Fiji / Java tool for manual, deformable 2D and 3D image registration. This tutorial will highlight the ways BigWarp uses the draft transformation specification for import and export. In particular, I will show use case where, given a moving image, a target image, and a set of transformations, bigwarp automatically determines which transformations to apply, in what direction (forward or inverse), and in what order. We will discuss how the Ome-Zarr transformation specification enables this functionality. If there is time and interest, I will show how BigWarp interpolates two transformations using a mask image, and how decomposing transformations into parts results in nicer behavior.

### Duration

30 minutes

### Desired time slot

- 10:00AM - 10:30AM
- 10:30AM - 11:00AM
- 11:00AM - 11:30AM
- 11:30AM - 12:00noon

Any of the above

**Comment by thewtex** [comment]
:fiji: @bogovicj fantastic! I added to the scheduled for 11 AM
