### ISSUE TITLE
Tutorial: an implementation decoupling the storage representation from the in-memory representation

### ISSUE THREAD

**Issue by LucaMarconato** [InsightSoftwareConsortium/GetYourBrainTogether#64]
### Tutorial description

Within the https://github.com/scverse/spatialdata/ library (a Python package for representing and processing spatial molecular datasets), we needed a way to represent vector and raster data across coordinate systems and store affine and non-linear coordinate transformations between them. We also needed to store this information in a language-agnostic way, so we decided to rely on the NGFF specification to represent the data.

Our first implementation was in the form of classes modeled closely after the NGFF design. While optimal for read/write operations, we soon realized that our API requirements needed to differentiate between the on-disk and in-memory representation. 

In the tutorial, we will discuss the lessons learned, the "selling points" and the limitations of our APIs, and the "behind the scenes", showing some technical details of our current implementation. We will also discuss a planned refactoring that will create a bridge between NGFF transformations and the xarray system of representing data coordinates.

### Duration

20-30 minutes

**Comment by thewtex** [comment]
@LucaMarconato beautiful! Added to the schedule.
