### ISSUE TITLE
Tutorial: Making Meaningful (Mouse) Mappings

### ISSUE THREAD

**Issue by ntustison** [InsightSoftwareConsortium/GetYourBrainTogether#65]
### Tutorial description

The Advanced Normalization Tools Ecosystem (ANTsX) is a comprehensive open-source software toolkit for generalized quantitative imaging with applicability to multiple organ systems, modalities, and animal species. In this tutorial, we illustrate the utility of ANTsX for generating precision spatial mappings of the mouse brain.   Specifically we discuss two recently developed ANTsX tools:

* The modeling of a velocity flow-based mapping spanning the spatiotemporal domain of a longitudinal trajectory which we apply to the Developmental Common Coordinate Framework—a longitudinal atlas demonstrating mouse development. 
* An automated structural morphological pipeline for determining volumetric and cortical thickness measurements analogous to the well-utilized ANTsX pipeline for human neuroanatomical structural morphology which  illustrates a general open-source framework for tailored brain parcellations.

Fully functional examples of the above are provided at a [dedicated GitHub repository](https://github.com/ntustison/ANTsXMouseBrainMapping) meant to accompany our recent [preprint](https://www.biorxiv.org/content/10.1101/2024.05.01.592056v1).  The tutorial will be given using the [ANTsPy toolkit](https://github.com/ANTsX/ANTsPy) with functionality self-contained tutorials [available](https://tinyurl.com/antsxtutorial).

### Duration

30 minutes

### Desired time slot

9:30 - 10 am
11:00 - 11:30 am
11:30 am - 12 pm

**Comment by thewtex** [comment]
Outstanding @ntustison !

Scheduled for 11:30 am - 12 pm
